M48
; DRILL file {KiCad (6.0.0-0)} date 2022 January 12, Wednesday 00:44:41
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-12T00:44:41+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
%
G90
G05
T1
X3.2785Y-3.6142
X3.2785Y-4.2126
X3.625Y-3.6142
X3.625Y-4.2126
T0
M30
